const S = {
  app: {
    minHeight: "100vh",
    background: "#030712", // Base dark background
    color: "#e2e8f0",
    fontFamily: "'DM Sans', system-ui, sans-serif",
    display: "flex",
  },
  // Updated main style to leave room for the absolute tailwind w-72 (288px) sidebar
  main: { flex: 1, marginLeft: "18rem", overflowY: "auto", minWidth: 0 },
  topbar: {
    background: "#0a0f1aee",
    backdropFilter: "blur(12px)",
    borderBottom: "1px solid #1f2937",
    padding: "14px 24px",
    display: "flex",
    marginLeft: "18rem",
    alignItems: "center",
    justifyContent: "space-between",
    position: "sticky",
    top: 0,
    zIndex: 50,
  },
  content: { padding: "28px 28px", maxWidth: 900, margin: "0 auto" },
  card: {
    background: "#0d1117",
    border: "1px solid #1f2937",
    borderRadius: 16,
    padding: 20,
  },
  btn: {
    background: "linear-gradient(135deg,#3b82f6,#6366f1)",
    border: "none",
    borderRadius: 10,
    padding: "10px 18px",
    color: "#fff",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  btnGhost: {
    background: "transparent",
    border: "1px solid #2d3748",
    borderRadius: 10,
    padding: "9px 16px",
    color: "#9ca3af",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  input: {
    background: "#161b22",
    border: "1px solid #2d3748",
    borderRadius: 10,
    padding: "10px 14px",
    color: "#e2e8f0",
    fontSize: 13,
    width: "100%",
    outline: "none",
  },
};
export default S;